# Generated by Django 5.0.6 on 2024-05-15 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('pokemon_id', models.IntegerField()),
                ('types', models.JSONField(blank=True, default=list)),
                ('abilities', models.JSONField(blank=True, default=list)),
                ('base_stats', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sprite_url', models.TextField()),
            ],
        ),
    ]
